download_statistics:
  description: >
    Downloads statistics for a given meter. Overrides all already downloaded data.
  fields:
    device_id:
      name: Target device
      description: The device to download statistics for.
      required: true
      selector:
        device:
          filter:
            - integration: tauron_amiplus
    start_date:
      name: Start date
      description: Start date of statistics to download.
      required: true
      selector:
        date:

force_price_recalculation:
  description: >
    Forces cost statistics to be recalculated using the current price sensor value.
    Only affects meters with cost statistics enabled.
  fields:
    device_id:
      name: Target device
      description: The device to recalculate cost statistics for.
      required: true
      selector:
        device:
          filter:
            - integration: tauron_amiplus

clear_cache:
  description: >
    Clear cache for a given meter.
  fields:
    device_id:
      name: Target device
      description: The device to clear cache.
      required: true
      selector:
        device:
          filter:
            - integration: tauron_amiplus
