name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v1

      - name: Zip tauron_amiplus dir
        run: |
          cd /home/runner/work/Home-Assistant-custom-components-Tauron-AMIplus/Home-Assistant-custom-components-Tauron-AMIplus/custom_components/tauron_amiplus
          zip tauron_amiplus.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/Home-Assistant-custom-components-Tauron-AMIplus/Home-Assistant-custom-components-Tauron-AMIplus/custom_components/tauron_amiplus/tauron_amiplus.zip
          asset_name: tauron_amiplus.zip
          tag: ${{ github.ref }}
          overwrite: true